[package]
name = "bbangcat_encryption"
version = "0.1.0"
edition = "2018"
license = "MIT"
repository = "https://github.com/fn79/BBangCatEncryption"
description = "BBang Cat Encryption"

[dependencies]
